### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by mIwr** [leif-ibsen/SwiftRSA#1]
It will be great, if you'll adopt the module and its dependencies (BigInt, Digest and ASN1, which are yours too) for CocoaPods

I'm working on project, which depends from SwiftRSA, and planning to make it available through SPM (your project supports SPM and it's OK) and CocoaPods (Not OK. Didn't find it at [cocoapods.org](https://cocoapods.org/pods/SwiftRSA))

**Comment by leif-ibsen** [comment]
I don't use CocoaPods myself, and I have no experience with it at all.
I'm afraid I cant't help you here.

**Comment by mIwr** [comment]
Ok, I see.
I have the possible soluiton: fork your repos, add CocoaPods support, create pull request. Only one question: may I publish modules by myself? All bio about author and upstream repo will be yours, but the repo link, from which will be loaded sources for pod dependency, will be mine (fork in fact)

**Comment by mIwr** [comment]
> I don't use CocoaPods myself, and I have no experience with it at all. I'm afraid I cant't help you here.

@leif-ibsen Ok, I see.
I can do it myself: fork your repos, add CocoaPods support, create pull requests. Only one question: may I publish modules at cocoapods.org by myself becouse you have no experience? All bio about author and upstream repos will be yours, but the repos' links, from which will be loaded sources for pod dependencies, will be mine (forks in fact)

P.S. I can edit pod dependency source links for yours and transfer pods ownership rights to you later

P.P.S If you agree with my proposition, re-open this issue plz

**Comment by leif-ibsen** [comment]
You should not create pull requests, because I would not accept them.You may publish modules yourself, thoughRegards Leif IbsenDen 23. aug. 2024 kl. 10.23 skrev mIwr ***@***.***>:﻿

I don't use CocoaPods myself, and I have no experience with it at all. I'm afraid I cant't help you here.

@leif-ibsen Ok, I see.
I have the possible soluiton: fork your repos, add CocoaPods support, create pull request. Only one question: may I publish modules by myself? All bio about author and upstream repos will be yours, but the repos' links, from which will be loaded sources for pod dependencies, will be mine (forks in fact)
